version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment:
      FLASK_APP: autoapp.py
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - "venv"
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flask lint
      - run:
          name: Test
          command: |
            . venv/bin/activate
            flask test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2
  publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
